# Generated by Django 5.2.7 on 2025-11-05 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userotpcode_attemps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_male', models.BooleanField(default=True)),
                ('height', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='قد (cm)')),
                ('weight', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='وزن (kg)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='BMI')),
                ('body_category', models.CharField(blank=True, max_length=100, verbose_name='دسته بدنی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
