# Generated by Django 5.2.7 on 2025-11-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='قد (cm)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='وزن (kg)'),
        ),
    ]
