# Generated by Django 5.2.7 on 2025-11-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_height_alter_profile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته بدنی'),
        ),
    ]
