# Generated by Django 5.2.7 on 2025-11-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_bmi_alter_profile_body_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body_category',
            field=models.CharField(blank=True, default='نامشخص', max_length=100, null=True, verbose_name='دسته بدنی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='وزن (kg)'),
        ),
    ]
