# Generated by Django 5.2.7 on 2025-11-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_addressuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressuser',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
    ]
