# Generated by Django 5.2.7 on 2025-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='اعتبار(تومان)'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.BigIntegerField(verbose_name='مبلغ تراکنش(تومان)'),
        ),
    ]
