# Generated by Django 5.2.7 on 2025-11-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_amount_alter_wallettransaction_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش کیف پول', 'verbose_name_plural': 'تراکنش های کیف پول'},
        ),
    ]
