# Generated by Django 5.2.7 on 2025-12-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0012_walletorder_delete_wallettransactionorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.PositiveBigIntegerField(verbose_name='تعداد روز')),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package_items', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='payment.packageorderitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار ارسال'), ('delivering', 'در حال ارسال'), ('delivered', 'تحویل شده'), ('failed', 'ناموفق')], default='pending', max_length=20)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='shipping.shipmentorder')),
            ],
        ),
    ]
