# Generated by Django 5.2.7 on 2025-11-16 11:40

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('تک وعده (نهار)', 'تک وعده (نهار)'), ('دو وعده (نهار و شام)', 'دو وعده (نهار و شام)')], default='تک وعده (نهار)', max_length=23, verbose_name='نوع وعده')),
                ('calories', models.CharField(blank=True, max_length=10, null=True, verbose_name='کالری (kcal)')),
                ('carbs', models.CharField(blank=True, max_length=10, null=True, verbose_name='کربوهیدرات (گرم)')),
                ('protein', models.CharField(blank=True, max_length=10, null=True, verbose_name='پروتئین (گرم)')),
                ('fat', models.CharField(blank=True, max_length=10, null=True, verbose_name='چربی (گرم)')),
                ('fiber', models.CharField(blank=True, max_length=10, null=True, verbose_name='فیبر (گرم)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/products')),
                ('ingredients', models.TextField(verbose_name='محتویات')),
                ('contraindications', models.TextField(blank=True, null=True, verbose_name='موارد منع مصرف')),
                ('indications', models.TextField(blank=True, null=True, verbose_name='موارد مصرف')),
                ('calories', models.CharField(blank=True, max_length=10, null=True, verbose_name='کالری (kcal)')),
                ('carbs', models.CharField(blank=True, max_length=10, null=True, verbose_name='کربوهیدرات (گرم)')),
                ('protein', models.CharField(blank=True, max_length=10, null=True, verbose_name='پروتئین (گرم)')),
                ('fat', models.CharField(blank=True, max_length=10, null=True, verbose_name='چربی (گرم)')),
                ('fiber', models.CharField(blank=True, max_length=10, null=True, verbose_name='فیبر (گرم)')),
                ('is_exist', models.BooleanField(default=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPriceWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_duration', models.IntegerField(default=1, verbose_name='تعداد هفته')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_week', to='shop.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم بسته')),
                ('image', models.ImageField(upload_to='uploads/packages')),
                ('add_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('feature', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='ویژگی های بسته')),
                ('important_note', models.TextField(blank=True, verbose_name='توضیحات مهم قبل از خرید')),
                ('package_info', models.TextField(blank=True, verbose_name='اطلاعات بسته')),
                ('composition', models.TextField(blank=True, help_text='توضیح درباره\u200cی مواد تشکیل\u200cدهنده، نوع غذاها، و اهداف سلامتی بسته', verbose_name='ترکیبات و جزئیات بسته')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='دسته بندی')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='shop.package', verbose_name='بسته مورد نظر'),
        ),
        migrations.CreateModel(
            name='ExtraOptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, verbose_name='آپشن')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='توضیحات')),
                ('exist_in_package', models.BooleanField(default=False, verbose_name='آپشن در بسته وجود دارد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_options', to='shop.package', verbose_name='بسته مورد نظر')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraOptionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, verbose_name='آپشن')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='توضیحات')),
                ('exist_in_package', models.BooleanField(default=False, verbose_name='آپشن در محصول وجود دارد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_options', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.productcategory'),
        ),
    ]
