# Generated by Django 5.2.7 on 2025-11-24 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaladItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'دسته بندی های آیتم سالاد',
            },
        ),
        migrations.CreateModel(
            name='SaladItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='اسم آیتم')),
                ('price', models.BigIntegerField(default=0, verbose_name='قیمت')),
                ('calories', models.CharField(max_length=10, verbose_name='کالری')),
                ('protein', models.CharField(max_length=10, verbose_name='پروتئین')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salad_items', to='shop.saladitemcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'آیتم سالاد',
                'verbose_name_plural': 'آیتم های سالاد',
            },
        ),
    ]
