# Generated by Django 5.2.7 on 2025-11-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_saladitemcategory_saladitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saladitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/salad_items'),
        ),
    ]
