# Generated by Django 5.2.7 on 2025-10-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='composition',
            field=models.TextField(blank=True, help_text='توضیح درباره\u200cی مواد تشکیل\u200cدهنده، نوع غذاها، و اهداف سلامتی بسته', verbose_name='ترکیبات و جزئیات بسته'),
        ),
        migrations.AddField(
            model_name='package',
            name='important_note',
            field=models.TextField(blank=True, verbose_name='توضیحات مهم قبل از خرید'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_info',
            field=models.TextField(blank=True, verbose_name='اطلاعات بسته'),
        ),
    ]
