# Generated by Django 5.2.7 on 2025-10-22 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_package_composition_package_important_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('تک وعده (نهار)', 'تک وعده (نهار)'), ('دو وعده (نهار و شام)', 'دو وعده (نهار و شام)')], default='تک وعده (نهار)', max_length=23, verbose_name='نوع وعده')),
                ('calories', models.CharField(blank=True, max_length=10, null=True, verbose_name='کالری (kcal)')),
                ('carbs', models.CharField(blank=True, max_length=10, null=True, verbose_name='کربوهیدرات (گرم)')),
                ('protein', models.CharField(blank=True, max_length=10, null=True, verbose_name='پروتئین (گرم)')),
                ('fat', models.CharField(blank=True, max_length=10, null=True, verbose_name='چربی (گرم)')),
                ('fiber', models.CharField(blank=True, max_length=10, null=True, verbose_name='فیبر (گرم)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.package', verbose_name='بسته مورد نظر')),
            ],
        ),
    ]
