# Generated by Django 5.2.7 on 2025-10-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='shop.package', verbose_name='بسته مورد نظر'),
        ),
    ]
