# Generated by Django 5.2.7 on 2025-10-23 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_meal_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraOptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, verbose_name='آپشن')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('exist_in_package', models.BooleanField(default=False, verbose_name='آپشن در بسته وجود دارد')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_options', to='shop.package', verbose_name='بسته مورد نظر')),
            ],
        ),
    ]
