# Generated by Django 5.2.7 on 2025-10-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_extraoptionpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration_week',
            field=models.IntegerField(default=1, help_text='حداکثر هفته ای که کاربر می تونه بسته رو خریداری کند', verbose_name='حداکثر هفته'),
        ),
    ]
