# Generated by Django 5.2.7 on 2025-10-23 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_package_duration_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraoptionpackage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_week',
        ),
        migrations.CreateModel(
            name='MealPriceWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_duration', models.IntegerField(default=1, verbose_name='تعداد هفته')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_week', to='shop.meal')),
            ],
        ),
    ]
