# Generated by Django 5.2.7 on 2025-10-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_extraoptionpackage_price_remove_meal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraoptionpackage',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
