# Generated by Django 5.2.7 on 2025-10-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_extraoptionpackage_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/products')),
                ('calories', models.CharField(blank=True, max_length=10, null=True, verbose_name='کالری (kcal)')),
                ('carbs', models.CharField(blank=True, max_length=10, null=True, verbose_name='کربوهیدرات (گرم)')),
                ('protein', models.CharField(blank=True, max_length=10, null=True, verbose_name='پروتئین (گرم)')),
                ('fat', models.CharField(blank=True, max_length=10, null=True, verbose_name='چربی (گرم)')),
                ('fiber', models.CharField(blank=True, max_length=10, null=True, verbose_name='فیبر (گرم)')),
                ('is_exist', models.BooleanField(default=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraOptionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, verbose_name='آپشن')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='توضیحات')),
                ('exist_in_package', models.BooleanField(default=False, verbose_name='آپشن در محصول وجود دارد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_options', to='shop.product')),
            ],
        ),
    ]
