# Generated by Django 5.2.7 on 2025-10-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contraindications',
            field=models.TextField(blank=True, null=True, verbose_name='موارد منع مصرف'),
        ),
        migrations.AddField(
            model_name='product',
            name='indications',
            field=models.TextField(blank=True, null=True, verbose_name='موارد مصرف'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='', verbose_name='محتویات'),
            preserve_default=False,
        ),
    ]
