# Generated by Django 5.2.7 on 2025-11-16 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0, verbose_name='مبلغ پرداختی')),
                ('status', models.CharField(choices=[('payed', 'پرداخت شده'), ('pending', 'در انتظار پرداخت'), ('completed', 'تکمیل شده'), ('processing', 'جاری')], default='pending', max_length=13, verbose_name='وضعیت سفارش')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
                ('payed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت سفارش')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل سفارش')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='شناسه سفارش')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='PackageOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergies', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.BigIntegerField(default=0, verbose_name='مبلغ')),
                ('meal_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mealpriceweek')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='payment.order', verbose_name='سفارش')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageOrderItemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.packageorderitem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.extraoptionpackage')),
            ],
        ),
        migrations.AddField(
            model_name='packageorderitem',
            name='extra_options',
            field=models.ManyToManyField(related_name='package_items', through='payment.PackageOrderItemExtra', to='shop.extraoptionpackage', verbose_name='آپشن های اضافه'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0, verbose_name='مبلغ')),
                ('status', models.CharField(default='pending', max_length=13, verbose_name='وضعیت تراکنش')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت تراکنش')),
                ('payed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل تراکنش')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پیگیری')),
                ('transaction_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='توکن تراکنش')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payment.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
    ]
