# Generated by Django 5.2.7 on 2025-11-18 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0, verbose_name='مبلغ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_items', to='payment.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrderItemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.productorderitem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.extraoptionproduct')),
            ],
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='extra_options',
            field=models.ManyToManyField(related_name='products_items', through='payment.ProductOrderItemExtra', to='shop.extraoptionproduct', verbose_name='آپشن های اضافه'),
        ),
    ]
