# Generated by Django 5.2.7 on 2025-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_productorderitem_productorderitemextra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderitem',
            name='quantity',
            field=models.BigIntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
