# Generated by Django 5.2.7 on 2025-11-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_productorderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorderitemextra',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='payment.packageorderitem'),
        ),
        migrations.AlterField(
            model_name='productorderitemextra',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='payment.productorderitem'),
        ),
    ]
