# Generated by Django 5.2.7 on 2025-11-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_packageorderitemextra_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payed', 'پرداخت شده'), ('pending', 'در انتظار پرداخت'), ('completed', 'تکمیل شده'), ('processing', 'جاری')], max_length=13, verbose_name='وضعیت سفارش'),
        ),
    ]
