# Generated by Django 5.2.7 on 2025-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='شماره سفارش'),
        ),
    ]
