# Generated by Django 5.2.7 on 2025-12-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_order_number'),
        ('shop', '0003_saladitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaladItemOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0, verbose_name='مبلغ')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.saladitem', verbose_name='آیتم')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salad_items', to='payment.order', verbose_name='سفارش')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
