# Generated by Django 5.2.7 on 2025-12-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_saladitemorderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaladItemOrderItem',
        ),
    ]
