# Generated by Django 5.2.7 on 2025-12-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_saladitemorderitem_saladorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saladorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salads_order', to='payment.order', verbose_name='سفارش'),
        ),
    ]
