# Generated by Django 5.2.7 on 2025-12-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_saladorder_order'),
        ('wallet', '0003_alter_wallettransaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0, verbose_name='مبلغ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transaction', to='payment.order', verbose_name='سفارش')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_payment', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
