# Generated by Django 5.2.7 on 2025-12-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_wallettransactionorderitem'),
        ('wallet', '0003_alter_wallettransaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('transaction_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='توکن تراکنش')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_orders', to='wallet.wallet')),
            ],
        ),
        migrations.DeleteModel(
            name='WalletTransactionOrderItem',
        ),
    ]
